;;; telega-decls.el --- Cross-file forward declarations  -*- lexical-binding: t -*-

;; Copyright (C) 2026 by Zajcev Evgeny.

;; This file is part of telega.el.

;;; Commentary:

;; Parts of telega require each other in a cycle, so some cross-file calls
;; cannot be resolved with a `require' and need a `declare-function'.
;; Keeping them here avoids scattering them over every file.
;;
;; A plain list of `declare-function' forms would not work: the byte
;; compiler only honours them in the file being compiled, so requiring
;; this file has no effect on the requiring file.  They are stored as
;; data and installed by a macro, which expands in the compiling file
;; where the compiler does see them:
;;
;;   (require 'telega-decls)
;;   (telega-declare-functions telega-ins)

;;; Code:

(eval-and-compile
  (defconst telega--forward-declarations
    '(
    (telega-community
      (telega-ins--image "telega-ins" (img &optional slice-num &rest props)))
    (telega-core
      (telega-custom-emoji--ensure "telega-emoji" (sticker))
      (telega-custom-emoji-get "telega-emoji" (custom-emoji-id))
      (telega-folder-name "telega-folders" (folder &optional no-properties))
      (telega--MessageTopic "telega-tdlib" (topic))
      (telega--getCustomEmojiStickers "telega-tdlib" (custom-emoji-ids &optional callback))
      (telega--change-text-property "telega-util" (start end prop value how &optional object))
      (telega--fmt-text-faces "telega-util" (fmt-text &optional _for-msg))
      (telega--split-by-text-prop "telega-util" (string prop &optional value-predicate))
      (telega-color-name-set-saturation-light "telega-util" (color-name saturation light))
      (telega-duration-human-readable "telega-util" (seconds &optional n long-p))
      (telega-stipple--box-button-body-gen "telega-util" (style))
      (telega-stipple-create "telega-util" (w h))
      (telega-stipple-fill-by-predicate "telega-util" (s predicate &optional no-cache-p))
      (telega-symbol "telega-util" (ending &optional image))
      (telega-time-seconds "telega-util" (&optional as-is))
      (telega-x-frame "telega-util" nil))
    (telega-folders
      (telega-custom-emoji--ensure "telega-emoji" (sticker))
      (telega-custom-emoji-get "telega-emoji" (custom-emoji-id))
      (telega-filter-chats "telega-filter" (chat-list &optional chat-temex))
      (telega-ins--box-button-delimiter "telega-ins" (bb-style prop-delim))
      (telega-ins--image "telega-ins" (img &optional slice-num &rest props))
      (telega-ins--text-button "telega-ins" (label &rest props))
      (telega--gen-ins-continuation-callback "telega-util" (show-loading-p &optional insert-func for-param))
      (telega-box-button--bracket-image "telega-util" (style bracket-prop &optional bracket-spec))
      (telega-completing-read-chat-list "telega-util" (prompt &optional chats-list sort-criteria))
      (telega-completing-read-folder "telega-util" (prompt &optional folder-names))
      (telega-completing-read-folder-icon-name "telega-util" (prompt &optional initial-input))
      (telega-completing-read-folder-list "telega-util" (prompt &optional folder-names))
      (telega-fmt-text "telega-util" (text &optional entity-type))
      (telega-fmt-text-desurrogate "telega-util" (fmt-text))
      (telega-msg-sender-title-for-completion "telega-util" (msg-sender))
      (telega-symbol "telega-util" (ending &optional image))
      (telega-symbol-emojify "telega-util" (emoji &optional image-spec)))
    (telega-inline
      (telega-chat-share-my-contact "telega-chat" (chat))
      (telega-chat-with "telega-chat" (chat-or-user))
      (telega-chatbuf--footer-update "telega-chat" nil)
      (telega-filter-chats "telega-filter" (chat-list &optional chat-temex))
      (telega-ins--audio "telega-ins" (msg &optional audio how music-symbol))
      (telega-ins--document-header "telega-ins" (doc &optional no-attach-symbol))
      (telega-ins--image "telega-ins" (img &optional slice-num &rest props))
      (telega-ins--location "telega-ins" (location))
      (telega-ins--voice-note "telega-ins" (msg &optional voice-note))
      (telega-msg-chat "telega-msg" (msg &optional offline-p))
      (telega-msg-sender "telega-msg" (tl-obj))
      (telega-msg-sender-title "telega-msg" (msg-sender &rest args))
      (telega-msg-sender-username "telega-msg" (msg-sender &optional with-prefix-p)))
    (telega-ins
      (telega-chat-bot-p "telega-chat" (chat))
      (telega-chat-member-my-status "telega-chat" (chat))
      (telega-chat-private-p "telega-chat" (chat))
      (telega-custom-emoji--ensure "telega-emoji" (sticker))
      (telega-custom-emoji-get "telega-emoji" (custom-emoji-id))
      (telega-custom-emoji-sticker-p "telega-emoji" (sticker))
      (telega-emoji-create-svg "telega-emoji" (emoji &optional cheight no-cache-p))
      (telega-describe-msg-sender "telega-msg" (sender))
      (telega-msg--replied-message "telega-msg" (msg))
      (telega-msg--replied-story "telega-msg" (msg))
      (telega-msg-by-me-p "telega-msg" (msg))
      (telega-msg-chat "telega-msg" (msg &optional offline-p))
      (telega-msg-checklist-task-add "telega-msg" (msg))
      (telega-msg-checklist-task-edit "telega-msg" (msg))
      (telega-msg-checklist-task-toggle "telega-msg" (msg))
      (telega-msg-emojis-only-p "telega-msg" (msg))
      (telega-msg-favorite-p "telega-msg" (msg))
      (telega-msg-marked-p "telega-msg" (msg))
      (telega-msg-media-spoiler-toggle "telega-msg" (msg))
      (telega-msg-open-content "telega-msg" (msg &optional clicked-p))
      (telega-msg-open-gift "telega-msg" (msg))
      (telega-msg-open-poll "telega-msg" (msg))
      (telega-msg-open-thread-or-topic "telega-msg" (msg))
      (telega-msg-p "telega-msg" (obj))
      (telega-msg-poll-add-option "telega-msg" (msg))
      (telega-msg-poll-stop "telega-msg" (msg))
      (telega-msg-public-forwards "telega-msg" (msg))
      (telega-msg-replies-count "telega-msg" (msg))
      (telega-msg-replies-has-unread-p "telega-msg" (msg))
      (telega-msg-resend "telega-msg" (msg))
      (telega-msg-rich-message-show-full "telega-msg" (msg))
      (telega-msg-sender "telega-msg" (tl-obj))
      (telega-msg-sender-brackets "telega-msg" (msg-sender))
      (telega-msg-sender-palette "telega-msg" (msg-sender))
      (telega-msg-sender-title "telega-msg" (msg-sender &rest args))
      (telega-msg-sender-title--special "telega-msg" (msg-sender &rest args))
      (telega-msg-sender-title-faces "telega-msg" (msg-sender &optional palette))
      (telega-msg-sender-unblock "telega-msg" (msg-sender &optional callback))
      (telega-msg-sender-username "telega-msg" (msg-sender &optional with-prefix-p))
      (telega-msg-summarize "telega-msg" (msg &optional to-language-code tone quiet))
      (telega-msg-translate "telega-msg" (msg &optional to-language-code tone quiet))
      (telega-sponsored-msg--action "telega-msg" (button))
      (telega-chat-notification-setting "telega-notifications" (chat setting &optional topic))
      (telega-voip--by-user-id "telega-voip" (user-id))
      (telega-voip--call-emojis "telega-voip" (call))
      (telega-msg--vvnote-play-speed-toggle "telega-vvnote" (msg))
      (telega-msg--vvnote-rewind "telega-vvnote" (msg step))
      (telega-msg--vvnote-stop "telega-vvnote" (msg))
      (telega-vvnote--waveform-decode "telega-vvnote" (waveform &optional raw-p))
      (telega-vvnote--waves-svg "telega-vvnote" (waves duration &optional played))
      (telega-vvnote-video--create-image "telega-vvnote" (note &optional _file with-noise-p))
      (telega-vvnote-video--create-image-one-line "telega-vvnote" (note &optional file))
      (telega-vvnote-video--svg "telega-vvnote" (framefile &key as-data-image-type progress with-noise-p))
      (telega-vvnote-video-ttl--create-image "telega-vvnote" (note &optional file))
      (telega-vvnote-video-ttl--create-image-one-line "telega-vvnote" (note &optional file))
      (telega-browse-url "telega-webpage" (url &optional in-web-browser)))
    (telega-media
      (telega-msg-chat "telega-msg" (msg &optional offline-p))
      (telega-msg-sender "telega-msg" (tl-obj))
      (telega-msg-sender-initials "telega-msg" (msg-sender))
      (telega-msg-sender-palette "telega-msg" (msg-sender))
      (telega-msg-sender-title "telega-msg" (msg-sender &rest args))
      (telega-msg-sender-title-faces "telega-msg" (msg-sender &optional palette))
      (telega-user-me "telega-user" (&optional locally-p))
      (telega-chars-in-height "telega-util" (pixels))
      (telega-chars-in-width "telega-util" (pixels))
      (telega-chars-xheight "telega-util" (n))
      (telega-chars-xwidth "telega-util" (n))
      (telega-color-name-as-hex-2digits "telega-util" (color))
      (telega-create-image "telega-util" (file-or-data &optional type data-p &rest props))
      (telega-directory-base-uri "telega-util" (directory))
      (telega-location-distance "telega-util" (loc1 loc2 &optional components-p))
      (telega-open-file "telega-util" (filename &optional msg))
      (telega-photo-preview--create-svg-one-line "telega-util" (filename data-p width height &optional video-p))
      (telega-svg-clip-path "telega-util" (svg id))
      (telega-svg-create "telega-util" (width height &rest args))
      (telega-svg-embed "telega-util" (svg image img-type datap &rest args))
      (telega-svg-embed-image-fitting "telega-util" (svg filename data-p img-width img-height &rest embed-attrs))
      (telega-svg-gradient "telega-util" (svg id type stops))
      (telega-svg-image "telega-util" (svg &rest props))
      (telega-svg-path "telega-util" (svg d &rest args))
      (telega-svg-progress "telega-util" (svg progress &optional with-border-p))
      (telega-svg-white-play-triangle-in-circle "telega-util" (svg))
      (telega-time-seconds "telega-util" (&optional as-is))
      (telega-video-preview--create-svg-one-line "telega-util" (filename data-p width height)))
    (telega-modes
      (telega-chat--info "telega-chat" (chat &optional locally-p))
      (telega-chat-buffer-auto-fill "telega-chat" (&optional win))
      (telega-chat-get "telega-chat" (chat-id &optional offline-p))
      (telega-chat-private-p "telega-chat" (chat))
      (telega-chatbuf--name "telega-chat" (chat))
      (telega-chatbuf--prompt-update "telega-chat" (&optional reset-aux))
      (telega-switch-important-chat "telega-chat" (chat))
      (telega-custom-emoji--ids-for-msg "telega-emoji" (msg &optional where))
      (telega-custom-emoji-get "telega-emoji" (custom-emoji-id))
      (telega--full-info "telega-info" (tlobj &optional _callback))
      (telega-describe-proxies "telega-info" (&rest _ignored))
      (telega-proxy-enabled "telega-info" (&optional added-proxies))
      (telega-proxy-last-used "telega-info" (&optional added-proxies)))
    (telega-msg
      (telega-chat--goto-thread "telega-chat" (chat thread-id &optional reply-msg-id))
      (telega-chat--info "telega-chat" (chat &optional locally-p))
      (telega-chat--supergroup "telega-chat")
      (telega-chat-channel-p "telega-chat" (chat))
      (telega-chat-me "telega-chat" (&optional can-create-p))
      (telega-chat-member-my-permissions "telega-chat" (chat))
      (telega-chat-user "telega-chat" (chat))
      (telega-chatbuf--gen-input-file "telega-chat" (filename &optional file-type preview-p upload-ahead-callback))
      (telega-chatbuf--goto-msg "telega-chat" (msg-id &optional highlight-p callback))
      (telega-chatbuf--goto-msg-content "telega-chat" (&optional text-position))
      (telega-chatbuf--last-msg "telega-chat" nil)
      (telega-chatbuf--last-read-inbox-msg-id "telega-chat" nil)
      (telega-chatbuf--msg-observable-p "telega-chat" (msg &optional node))
      (telega-chatbuf-msg--pp "telega-chat" (msg &optional for-preview-p))
      (telega-describe-chat "telega-chat" (chat))
      (telega-custom-emoji--ids-for-msg "telega-emoji" (msg &optional where))
      (telega-custom-emoji-get "telega-emoji" (custom-emoji-id))
      (telega-custom-emoji-id "telega-emoji" (sticker))
      (telega-custom-emoji-sticker-p "telega-emoji" (sticker))
      (telega-ins--custom-emoji-stickersets "telega-emoji" (custom-action))
      (telega-edit-file-save-buffer "telega-modes" nil))
    (telega-notifications
      (telega-chatbuf--msg-observable-p "telega-chat" (msg &optional node))
      (telega-describe-chat "telega-chat" (chat)))
    (telega-rich-text
      (telega-custom-emoji--image "telega-emoji" (obj &key (prop-name :custom_emoji_id) (cheight 1) alt-text))
      (telega-ins--audio "telega-ins" (msg &optional audio how music-symbol))
      (telega-ins--date "telega-ins" (timestamp &optional fmt-type))
      (telega-ins--image "telega-ins" (img &optional slice-num &rest props))
      (telega-ins--image-slices "telega-ins" (image &optional props slice-func))
      (telega-ins--photo "telega-ins" (photo &optional msg limits show-details))
      (telega-ins--video "telega-ins" (msg &optional video how))
      (telega-ins--voice-note "telega-ins" (msg &optional voice-note))
      (telega-browse-url "telega-webpage" (url &optional in-web-browser))
      (telega-webpage--ins-animation "telega-webpage" (animation))
      (telega-webpage-goto-anchor "telega-webpage" (name)))
    (telega-server
      (telega-filters--redisplay "telega-filter" nil)
      (telega--getOption "telega-tdlib" (prop-kw &optional callback))
      (telega-docker--container-id-filename "telega-util" nil)
      (telega-docker-run-cmd "telega-util" (cmd &rest volumes))
      (telega-time-seconds "telega-util" (&optional as-is)))
    (telega-sort
      (telega-chat-user "telega-chat" (chat))
      (telega--full-info "telega-info" (tlobj &optional _callback)))
    (telega-sticker
      (telega-chatbuf-custom-emoji-insert "telega-chat" (sticker &optional emoji))
      (telega-msg-redisplay "telega-chat" (msg &optional node))
      (telega-custom-emoji-from-sticker "telega-emoji" (sticker))
      (telega-custom-emoji-sticker-p "telega-emoji" (sticker))
      (telega-emoji-backward "telega-emoji" nil)
      (telega-emoji-fe0f-p "telega-emoji" (emoji))
      (telega-emoji-name "telega-emoji" (emoji))
      (telega-ins--image "telega-ins" (img &optional slice-num &rest props))
      (telega-ins--image-slices "telega-ins" (image &optional props slice-func))
      (telega-animation--ffplay-callback "telega-msg" (_proc frame anim)))
    (telega-story
      (telega-chat--pop-to-buffer "telega-chat" (chat &optional no-history-load))
      (telega-chat-get "telega-chat" (chat-id &optional offline-p))
      (telega-chat-user "telega-chat" (chat))
      (telega-chatbuf-input-insert "telega-chat" (imc))
      (telega-msg-redisplay "telega-chat" (msg &optional node))
      (telega-filter-chats "telega-filter" (chat-list &optional chat-temex))
      (telega-image-view-file "telega-modes" (tl-file &optional for-msg))
      (telega-msg-chat "telega-msg" (msg &optional offline-p))
      (telega-msg-sender "telega-msg" (tl-obj))
      (telega-msg-sender-palette "telega-msg" (msg-sender)))
    (telega-tdlib
      (telega-chat-secret-p "telega-chat" (chat))
      (telega-custom-emoji--ensure "telega-emoji" (sticker))
      (telega-i18n "telega-i18n" (key &rest args))
      (telega-msg-p "telega-msg" (obj))
      (telega-msg-sender "telega-msg" (tl-obj))
      (telega-chat-notification-scope "telega-notifications" (scope-type))
      (telega-story--ensure "telega-story" (story &optional no-root-update))
      (telega-topic-id "telega-topic" (topic))
      (telega-fmt-text "telega-util" (text &optional entity-type))
      (telega-time-seconds "telega-util" (&optional as-is)))
    (telega-tme
      (telega-chat--goto-thread "telega-chat" (chat thread-id &optional reply-msg-id))
      (telega-chat-bot-p "telega-chat" (chat))
      (telega-chat-user "telega-chat" (chat))
      (telega-chatbuf--chat-update "telega-chat" (&rest dirtiness))
      (telega-chat-username "telega-msg")
      (telega-msg-at "telega-msg" (&optional pos msg-predicate))
      (telega-msg-get "telega-msg" (chat msg-id &optional callback))
      (telega-msg-goto-highlight "telega-msg" (msg))
      (telega-msg-open-content "telega-msg" (msg &optional clicked-p)))
    (telega-topic
      (telega-chat--pop-to-buffer "telega-chat" (chat &optional no-history-load))
      (telega-chatbuf--get-create "telega-chat" (chat &optional no-history-load))
      (telega-chatbuf-filter-by-topic "telega-chat" (topic &optional start-msg-id))
      (telega-custom-emoji--ensure "telega-emoji" (sticker))
      (telega-custom-emoji-get "telega-emoji" (custom-emoji-id))
      (telega-ins--chat "telega-ins" (chat))
      (telega-ins--date "telega-ins" (timestamp &optional fmt-type))
      (telega-ins--msg-sender "telega-ins" (msg-sender &key with-title with-avatar-p with-username-p with-brackets-p (with-badges-p t) (with-title-faces-p t) with-palette trail-inserter))
      (telega-ins--topic-title "telega-ins" (topic &key with-icon-p with-maybe-pin-p (with-brackets-p t)))
      (telega-msg-chat "telega-msg" (msg &optional offline-p))
      (telega-msg-for-interactive "telega-msg" nil)
      (telega-msg-sender "telega-msg" (tl-obj))
      (telega-msg-sender-brackets "telega-msg" (msg-sender))
      (telega-chat-notification-setting "telega-notifications" (chat setting &optional topic))
      (telega-chat-button-action "telega-root" (chat))
      (telega-sticker--image "telega-sticker" (sticker &optional image-create-fun cache-prop))
      (telega-chars-xheight "telega-util" (n))
      (telega-chars-xwidth "telega-util" (n))
      (telega-color-name-as-hex-2digits "telega-util" (color))
      (telega-link-props "telega-util" (link-type link-to &rest props))
      (telega-svg-create "telega-util" (width height &rest args))
      (telega-svg-forum-topic-icon "telega-util" (svg width &rest args))
      (telega-svg-image "telega-util" (svg &rest props))
      (telega-symbol "telega-util" (ending &optional image)))
    (telega-transient
      (telega-chat--supergroup "telega-chat")
      (telega-chat-leave "telega-chat" (chat &optional keep-chatbuf))
      (telega-chat-me "telega-chat" (&optional can-create-p))
      (telega-chat-secret-p "telega-chat" (chat))
      (telega-chat-title "telega-chat" (chat &optional fmt-type no-badges))
      (telega-chat-toggle-archive "telega-chat" (chat))
      (telega-chat-user "telega-chat" (chat))
      (telega-chatbuf--chat-update "telega-chat" (&rest dirtiness))
      (telega-chatbuf--filter-match-msg-p "telega-chat" (msg))
      (telega-chatbuf--input-imcs "telega-chat" (markup-name &optional input))
      (telega-chatbuf--node-by-msg-id "telega-chat" (msg-id))
      (telega-chatbuf--prompt-update "telega-chat" (&optional reset-aux))
      (telega-chatbuf--redisplay-node "telega-chat" (node))
      (telega-chatbuf-filter-by-saved-messages-tag "telega-chat" (tag &optional query))
      (telega-chatbuf-msg-marks-toggle "telega-chat" nil)
      (telega-msg-redisplay "telega-chat" (msg &optional node))
      (telega-msg--content-file "telega-msg" (msg))
      (telega-msg--set-link-preview-options "telega-msg" (msg tl-lp-options))
      (telega-msg-at "telega-msg" (&optional pos msg-predicate))
      (telega-msg-chat "telega-msg" (msg &optional offline-p))
      (telega-msg-content-text "telega-msg" (msg &optional with-speech-recognition-p))
      (telega-msg-disable-link-preview "telega-msg" (msg))
      (telega-msg-for-interactive "telega-msg" nil)
      (telega-msg-goto "telega-msg" (msg &optional highlight-p callback))
      (telega-msg-replies-count "telega-msg" (msg))
      (telega-msg-sender "telega-msg" (tl-obj))
      (telega-msg-sender--verification-badges "telega-msg" (v-status))
      (telega-msg-sender-block "telega-msg" (msg-sender &optional callback))
      (telega-msg-sender-title "telega-msg" (msg-sender &rest args))
      (telega-msg-summarize "telega-msg" (msg &optional to-language-code tone quiet))
      (telega-msg-translate "telega-msg" (msg &optional to-language-code tone quiet))
      (telega-browse-url "telega-webpage" (url &optional in-web-browser)))
    (telega-user
      (telega-emoji-status--animate "telega-emoji" (emoji-status))
      (telega-ins--emoji-status "telega-emoji" (emoji-status))
      (telega--full-info "telega-info" (tlobj &optional _callback))
      (telega--info "telega-info" (tlobj-type tlobj-id &optional locally-p))
      (telega-info--insert-user "telega-info" (user &optional chat))
      (telega-ins--chat-member "telega-ins" (member))
      (telega-ins--contact "telega-ins" (contact &key (with-avatar-p t) (with-title-faces-p t) (with-online-status-p t) (with-username-p t) (with-phone-p t)))
      (telega-ins--image "telega-ins" (img &optional slice-num &rest props))
      (telega-ins--user "telega-ins" (user &optional member show-phone-p))
      (telega-msg-sender--verification-badges "telega-msg" (v-status))
      (telega-msg-sender-block "telega-msg" (msg-sender &optional callback))
      (telega-msg-sender-title "telega-msg" (msg-sender &rest args))
      (telega-msg-sender-unblock "telega-msg" (msg-sender &optional callback))
      (telega-msg-sender-username "telega-msg" (msg-sender &optional with-prefix-p))
      (telega-chats-compare "telega-sort" (criteria chat1 chat2))
      (telega-box-button--bracket-image "telega-util" (style bracket-prop &optional bracket-spec))
      (telega-completing-read-user "telega-util" (prompt &optional users))
      (telega-symbol "telega-util" (ending &optional image)))
    (telega-util
      (telega-chat--supergroup "telega-chat")
      (telega-chat-create "telega-chat" (chat-type))
      (telega-chat-topics "telega-chat" (chat))
      (telega-chat-user "telega-chat" (chat))
      (telega-chatbuf-filter-hashtag "telega-chat" (hashtag &optional by-sender-p))
      (telega-custom-emoji-choose "telega-emoji" (&optional custom-action))
      (telega-custom-emoji-get "telega-emoji" (custom-emoji-id))
      (telega-emoji--image-cache-get "telega-emoji" (emoji cheight))
      (telega-emoji--image-cache-put "telega-emoji" (emoji cheight image))
      (telega-emoji-create-svg "telega-emoji" (emoji &optional cheight no-cache-p))
      (telega-emoji-name "telega-emoji" (emoji))
      (telega-filter-chats "telega-filter" (chat-list &optional chat-temex))
      (telega--full-info "telega-info" (tlobj &optional _callback))
      (telega-ins--chat "telega-ins" (chat))
      (telega-ins--date-time-formatting "telega-ins" (timestamp ts-fmt))
      (telega-ins--image "telega-ins" (img &optional slice-num &rest props))
      (telega-ins--msg-sender "telega-ins" (msg-sender &key with-title with-avatar-p with-username-p with-brackets-p (with-badges-p t) (with-title-faces-p t) with-palette trail-inserter))
      (telega-ins--topic-title "telega-ins" (topic &key with-icon-p with-maybe-pin-p (with-brackets-p t)))
      (telega-describe-msg-sender "telega-msg" (sender))
      (telega-msg-at "telega-msg" (&optional pos msg-predicate))
      (telega-msg-blockquote-expand-toggle "telega-msg" (msg))
      (telega-msg-chat "telega-msg" (msg &optional offline-p))
      (telega-msg-open-media-timestamp "telega-msg" (msg timestamp &optional error-p))
      (telega-msg-sender "telega-msg" (tl-obj))
      (telega-msg-sender-palette "telega-msg" (msg-sender))
      (telega-msg-text-spoiler-toggle "telega-msg" (msg))
      (telega-sort-chats "telega-sort" (criteria chats))
      (telega-sticker--image "telega-sticker" (sticker &optional image-create-fun cache-prop))
      (telega-tme-open-tdlib-link "telega-tme" (tdlib-link)))
    (telega-voip
      (telega-chat-by "telega-chat" (pred))
      (telega-chat-group-call "telega-chat" (&optional chat))
      (telega-root-aux-redisplay "telega-root" (&optional item))
      (telega-root-view--update "telega-root" (on-update-prop &rest args)))
    (telega-vvnote
      (telega-msg-redisplay "telega-chat" (msg &optional node))
      (telega-msg-for-interactive "telega-msg" nil)
      (telega-msg-open-content "telega-msg" (msg &optional clicked-p)))
    (telega-webpage
      (telega-animation--ffplay-callback "telega-msg" (_proc frame anim)))
      )
    "Forward declarations needed by each telega module.
Each entry is (MODULE (FUNCTION FILE [ARGLIST]) ...)."))

(defmacro telega-declare-functions (module)
  "Declare the functions MODULE calls but cannot `require'."
  (cons 'progn
        (mapcar (lambda (d)
                  `(declare-function ,(nth 0 d) ,(nth 1 d) ,@(cddr d)))
                (cdr (assq module telega--forward-declarations)))))

(defun telega-decls--definition (fn file)
  "Find how FN is defined in FILE.
Return (ARGLIST) for a definition written with an argument list,
`aliased' for one made with `defalias', or nil when FN is not found."
  (let ((path (locate-library (symbol-name file))))
    (when (and path (string-suffix-p ".elc" path))
      (setq path (substring path 0 -1)))
    (when (and path (file-exists-p path))
      (with-temp-buffer
        (insert-file-contents path)
        (emacs-lisp-mode)
        (goto-char (point-min))
        (cond
         ((re-search-forward
           (concat "^\\s-*(\\(?:cl-\\)?\\(?:defun\\|defsubst\\|defmacro\\|define-inline\\)\\s-+"
                   (regexp-quote (symbol-name fn)) "\\s-")
           nil t)
          (skip-chars-forward " \t\n")
          (when (looking-at "(")
            (list (car (read-from-string
                        (buffer-substring-no-properties
                         (point) (progn (forward-sexp 1) (point))))))))
         ((save-excursion
            (goto-char (point-min))
            (re-search-forward (concat "^\\s-*(defalias\\s-+'"
                                       (regexp-quote (symbol-name fn)) "\\_>")
                               nil t))
          'aliased))))))

(defun telega-decls-check ()
  "Check every entry in `telega--forward-declarations'.
Return a list of human readable problems, empty when all entries
match the sources they name.  Run it after moving or renaming a
function that other telega files declare."
  (interactive)
  (let (problems)
    (dolist (entry telega--forward-declarations)
      (dolist (decl (cdr entry))
        (let* ((fn (nth 0 decl))
               (file (intern (nth 1 decl)))
               (declared (nth 2 decl))
               (found (telega-decls--definition fn file)))
          (cond
           ((null found)
            (push (format "%s: %s is not defined in %s" (car entry) fn file)
                  problems))
           ((and (consp found) (cddr decl) (not (equal (car found) declared)))
            (push (format "%s: %s arglist is %S, declared %S"
                          (car entry) fn (car found) declared)
                  problems))))))
    (when (called-interactively-p 'interactive)
      (message "telega-decls-check: %d problem(s)" (length problems)))
    (nreverse problems)))

(provide 'telega-decls)

;;; telega-decls.el ends here
